export const tabBarIcons = {
  home: require('../../assets/ledger/icons/tab/icon_home_96.png'),
  bills: require('../../assets/ledger/icons/tab/icon_bill_96.png'),
  addRecord: require('../../assets/ledger/icons/tab/icon_plus_96.png'),
  report: require('../../assets/ledger/icons/tab/icon_chart_96.png'),
  mine: require('../../assets/ledger/icons/tab/icon_user_96.png'),
} as const;

export const featureIcons = {
  home: require('../../assets/ledger/icons/tab/icon_home_96.png'),
  user: require('../../assets/ledger/icons/tab/icon_user_96.png'),
  wallet: require('../../assets/ledger/icons/feature/icon_wallet_96.png'),
  budget: require('../../assets/ledger/icons/feature/icon_budget_96.png'),
  report: require('../../assets/ledger/icons/feature/icon_report_96.png'),
  food: require('../../assets/ledger/icons/feature/icon_food_96.png'),
  car: require('../../assets/ledger/icons/feature/icon_car_96.png'),
  shop: require('../../assets/ledger/icons/feature/icon_shop_96.png'),
  chart: require('../../assets/ledger/icons/tab/icon_chart_96.png'),
  medical: require('../../assets/ledger/icons/feature/icon_medical_96.png'),
  study: require('../../assets/ledger/icons/feature/icon_study_96.png'),
  search: require('../../assets/ledger/icons/feature/icon_search_96.png'),
  settings: require('../../assets/ledger/icons/feature/icon_settings_96.png'),
  export: require('../../assets/ledger/icons/feature/icon_export_96.png'),
  backup: require('../../assets/ledger/icons/feature/icon_backup_96.png'),
  tag: require('../../assets/ledger/icons/feature/icon_tag_96.png'),
  calendar: require('../../assets/ledger/icons/feature/icon_calendar_96.png'),
  asset: require('../../assets/ledger/icons/feature/icon_asset_96.png'),
  income: require('../../assets/ledger/icons/feature/icon_income_96.png'),
  delete: require('../../assets/ledger/icons/feature/icon_delete_96.png'),
} as const;
